AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-ghactions-demo
  Sample SAM Template for aws-sam-ghactions-demo
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  DeploymentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: TenantPipeline/resources/
      Handler: lambda-deploy-tenant-stack.lambda_handler
      Runtime: python3.8
      Policies:
      - Statement:
        - Sid: lambdapolicy
          Effect: Allow
          Action: '*'
          Resource: '*'