name: Backend application

on: workflow_dispatch

jobs:
  Build:
    name: Build Sam App
    runs-on: ubuntu-latest

    steps:
      - name: Create folders
        run: |
          mkdir repo

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./repo

      - name: Build the app
        working-directory: ./repo/server
        run: |
          sam build --use-container -t tenant-template.yaml
          
  DeploytoDev:
    needs: [Build]
    name: Deploy stack to AWS Dev Account
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./repo

      - name: Configure AWS credentials
        id: dev_creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Dev Account
        working-directory: ./repo/server
        run: |
          sam deploy --config-env dev -t tenant-template.yaml --no-confirm-changeset --stack-name serverless-saas-app-ghactions-dev --s3-bucket aws-sam-dev-ghactions

  DeploytoProd:
    needs: [Build, DeploytoDev]
    name: Deploy stack to AWS Prod Account
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./repo
          
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy the Prod if dev deployment succeeds
        working-directory: ./repo/server
        run: |
          sam deploy --config-env prod -t tenant-template.yaml --no-confirm-changeset --stack-name serverless-saas-app-ghactions --s3-bucket aws-sam-prod-ghactions
